ads-b:
  description: "This feed transforms ADS-B log data to events."
  output: streaming
  parser:
    description: "A JSON parser configured for ADS-B log data."
    class: c3.ingest.parsers.json.JsonParser
    vis: "U"
    config:
      group-by: "/acList"
      mappings:
        "/acList/Call": "//adsb//callsign"
        "/acList/FSeen": "//time//receipt"
        "/acList/Icao": "//adsb//icao"
#        "/acList/Cos": "//adsb//cos"
      ingest-info:
        file-name: "parsers.file.name"
        file-size: "parsers.file.size"
        record-number: "parsers.record.number"
  transforms:
    - description: "Set the kronos event type"
      class: c3.ingest.transforms.event.type.SetType
      config:
        value: "ADS-B"
    - description: "Assign an idempotent ID to the event."
      class: c3.ingest.extra.transforms.event.id.ShortHashIdFromFields
      config:
        fields: ["parsers.file.name", "parsers.file.size", "parsers.record.number"]
    - description: "Clear out the file info values and record number."
      class: c3.ingest.transforms.event.field.RemoveAll
      config:
        fields: ["parsers.file.size", "parsers.record.number", "parsers.file.name"]
    - description: "Remove leading square brace from a time of request."
      class: c3.ingest.extra.transforms.event.field.ReplaceSubstring
      config:
        "//time//receipt":
          "/Date\\(": ""
          "\\)/": ""
    - description: "add a timestamp to the event"
      class: c3.ingest.transforms.event.time.TimeFromField
      config:
        field: "//time//receipt"
    - description: "Convert timestamp to an Instant datatype"
      class: c3.ingest.transforms.event.field.ConvertValue
      config:
        "//time//receipt":
          - instant: millis
