ads-b:
  description: "This feed transforms ADS-B log data to events."
  output: streaming
  parser:
    description: "A JSON parser configured for ADS-B log data."
    class: bdp.ingest.parsers.json.JsonParser
    vis: "U"
    config:
      group-by: "/acList"
      mappings:
        "/acList/Call": "//adsb//callsign"
        "/acList/FSeen": "//time//receipt"
        "/acList/Icao": "//adsb//icao"
        "/acList/Alt": "//adsb//alt"
        "/acList/Lat": "//latitude"
        "/acList/Long": "//longitude"
        "/acList/Spd": "//adsb//speed"
        "/acList/Cou": "//country"
      ingest-info:
        file-name: "parsers.file.name"
        file-size: "parsers.file.size"
        record-number: "parsers.record.number"
  transforms:
    - description: "Set the kronos event type"
      class: bdp.ingest.transforms.event.type.SetType
      config:
        value: "ADS-B"
    - description: "Assign an idempotent ID to the event."
      class: bdp.ingest.transforms.event.id.HashIdFromFields
      config:
        fields: ["parsers.file.name", "parsers.file.size", "parsers.record.number"]
    - description: "Clear out the file info values and record number."
      class: bdp.ingest.transforms.event.field.RemoveAll
      config:
        fields: ["parsers.file.size", "parsers.record.number", "parsers.file.name"]
    - description: "Remove leading square brace from a time of request."
      class: bdp.ingest.extra.transforms.event.field.ReplaceSubstring
      config:
        "//time//receipt":
          "/Date\\(": ""
          "\\)/": ""
    - description: "add a timestamp to the event"
      class: bdp.ingest.transforms.event.time.TimeFromField
      config:
        field: "//time//receipt"
    - description: "Convert timestamp to an Instant datatype"
      class: bdp.ingest.transforms.event.field.ConvertValue
      config:
        "//time//receipt":
          - instant: millis
        "//adsb//alt": "integer"
        "//adsb//speed": "double"
        "//longitude": "double"
        "//latitude": "double"
