email:
  description: "This feed transforms Jeb Bush's archived emails"
  output: streaming
  parser:
    description: "An email parser."
    class: com.eitccorp.demo.sofwerx.parser.EmailParser
    vis: "U"
  transforms:
    - description: "Set the kronos event type"
      class: bdp.ingest.transforms.event.type.SetType
      config:
        value: "EMAIL"
    - description: "add Kronos timestamp from datetime field"
      class: bdp.ingest.transforms.event.time.AdvancedTime
      config:
        formats:
          - "//datetime//smtpheader": "E, MMM d, Y h:m aa"
          - "//datetime": "MM/dd/YYYY hh:mm:ss aa"
#    - description: "Convert IP SRC and time of request field types"
#      class: bdp.ingest.transforms.event.field.ConvertValue
#      config:
#        "//datetime":
#          - instant: "MM/dd/yyyy hh:mm aa"
#